#!url=🟥https://raw.githubusercontent.com/Peng-Lx/lxpscript/master/LanceX/Uclock/Spotify.module
#!name=🟩Spotify🟪不能设置为超高音质
#!author=🔜By 🟦 @app2smile


[Script]
Spotify-json = pattern=^https?:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,enable=true,requires-body=true,type=http-response,script-path=https://ghproxy.com/https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
Spotify-proto = pattern=^https?:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,enable=true,requires-body=true,type=http-response,script-path=https://ghproxy.com/https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js



[MITM]
hostname = %APPEND% spclient.wg.spotify.com
