#!url=🟥https://raw.githubusercontent.com/Peng-Lx/lxpscript/master/LanceX/Uclock/Spotify.module
#!name=🟩喜马拉雅 vip
#!author=🔜By 🟦 @WeiRen0

[URL Rewrite]
"^http[s]?:\/\/openapi\.mysteel\.com/v5/getAdv.htm - reject
"^http[s]?.+ulogs.umeng.com - reject
"^http[s]?.+gslbali.ximalaya.com - reject
"^http[s]?.+adse.ximalaya.com - reject
"^http[s]?.+gslbtx.ximalaya.com - reject
"^http[s]?.+location.ximalaya.com - reject
"^http[s]?.+passport.ximalaya.com - reject
"^http[s]?.+adbehavior.ximalaya.com - reject
"^http[s]?.+ad.ximalaya.com - reject
"^http[s]?.+audid-api.taobao.com - reject


[Script]
喜马拉雅1 = pattern=^http[s]?:\/\/((.+ximalaya.+)|(.+xmcdn.+)).*\/(playpage\/tabs\/v2|v1\/album\/track\/ts|v1\/album\/price|v2\/homePage|business-vip-presale-mobile-web\/page\/ts|vip\/v1\/recommand|track\/v3\/baseInfo|v1\/module\/data\/dynamic|basicInfo\/dynamic\/ts).*$,enable=true,requires-body=true,type=http-response,script-path=https://ghproxy.com/https://raw.githubusercontent.com/WeiRen0/Scripts/main/XMVIPTY2.js
喜马拉雅2 = pattern=^http[s]?:\/\/((.+ximalaya.+)|(.+xmcdn.+))\/mobile-playpage\/track\/v3\/baseInfo\/ts,enable=true,requires-body=true,type=http-reques,script-path=https://ghproxy.com/https://raw.githubusercontent.com/WeiRen0/Scripts/main/xmty2.js


[MITM]
hostname = %APPEND% 180.153.*.*,*xima*,*xmcdn*,*.ximalaya.com,*.xmcdn.com,180.153.255.*,180.153.140.*,180.153.250.*,114.80.99.*,114.80.139.237,114.80.161.29,1.62.62.64,51*.com,182.254.*.*
